= Definition of Done and Ambient Requirements

The Definition of Done (DoD) describes the criteria for tasks to be fulfilled in 
order to be considered done and closed. All of the following criterias must be met:

* Acceptance criterias from the user story are fully implemented and met.
* Automated tests for the implemented features are in existence, are following the acceptance criterias in full and are running successfully. 
* Code coverage is not decreased by the implementation and the implementation of the tests.
* The code is properly documented with source code comments.
* The features and design decisions are properly documented in devdoc.

In addition, we have some "ambient requirements" that must be met for all implemented features. These requirements are 
not contained in the user stories, because they apply to every story by default. The following functional/non-functional requirements
are mandatory for all implementations:

* The UI implementation follows the UX guidelines in features, usability, and design. If not, state reason (UX not available yet for example).
* To all web resources in the application can be deep linked to. URL patterns are stable and clean.

