sudo: required

services:
  - docker

before_install:
  - TRAVIS_ENABLED=true

script:
  - sh generate.sh

after_error: 
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_success:      
  - cd output/docs
  - git init
  - git config user.name "${GH_USER}"
  - git config user.email "${GH_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/fabric8-services/fabric8-devdoc" master:gh-pages > /dev/null 2>&1
