language: ruby
rvm:
- 2.2.1
sudo: false
script: bundle exec jekyll build && bundle exec jekyll build && bundle exec rake deploy
addons:
  apt:
    packages:
    - graphviz
env:
  global:
  - secure: vS6aFihEA2rgGgrXcbrlxubQViSTKK+jWkadC9USd4mq6BFAxufIN84FNosn7uG3OCu3s+Y7xUgS9DKq7aBq29soF7ob8gG2reunrDECGOnoRPLsbNlWXraRMnN2I15cgGVsReQEB8IRztq3QYGspxNPDHnzjbf9juLw9JobrU5dttZd1Mb1bMg4I/Fl2dX4I75bvvPJQkH52JUG+OmPqH7EqLSlvoh1OtL1pDApN4zmCwvvjGkU3+pJuJMZ4YKAGDAoKjgRa58MBMp9L+wE7dZZtzuU39sTjTllO89sV+16twPBBTyCXfuufDeNNmIJghSDXpAF9lxQNCG9CWHv/RMnziThloqgsFvUnPcrGIk4qt4VlSLlukicw+GbBMwZNbwdwSMnYINtFIuVuQe5AKJiRJXlDEhGinmgsPF5SGIigRTgyUuKzQMX4XR/krVstWh6Xu+miP8Dz4CPmr8z5WaIn1zYZF9cvSLWQzeOU/1SsQ0Mqnr3mPFxoHiX6oUr2bVWhg/uPGp0Sb8ilzvQiFyi+gTU5wBVcSumO1C7jXY7JXCc1cxbhZfKVQUuBPP0z2TxFzg7mKgHG7oPLR7F+BjGrGyzwK0uL0VdlwEyEOjLL3DbyX3WJfXjCfBiP1aOZeKkwz41E3vsOf6oRORclH55IhUgDmaLuCWTRZ7kS3c=
